#!/usr/bin/env bash
# test_atm339_reconfigure_detection.sh — hermetic test of the ATM-339
# reconfigure-on-prefix-change detection logic in compile-libvlc.sh +
# build-atmosphere-vlc-player.sh.
#
# WHAT THIS PROVES (anti-bluff, §11.4 / §11.4.6):
#   The ATM-339 fix wipes a VLC build-android-<tuple> dir ONLY when its
#   config.status was generated for a DIFFERENT absolute contrib prefix
#   than the one the current checkout location would use. This test
#   reproduces the exact decision predicate from the source fix against
#   two synthetic config.status fixtures and asserts:
#     CASE 1 same-prefix    → NO reconfigure (build dir preserved)
#     CASE 2 changed-prefix → reconfigure triggered (build dir wiped)
#     CASE 3 no config.status (fresh)       → no spurious wipe (guard is
#            on the existing-config.status path; configure runs naturally)
#
# WHY HERMETIC: the real failure only manifests inside a §12.9 container
# build (a multi-hour AOSP rebuild — REQUIRES_BUILD, out of scope here).
# This test stubs the heavy build entirely: it creates fake build dirs +
# config.status files mirroring what `configure` records, runs ONLY the
# detection predicate, and observes whether the wipe fired. The predicate
# tested is byte-identical (modulo variable names) to the one shipped in
# compile-libvlc.sh §586+ and build-atmosphere-vlc-player.sh.
#
# A wrong predicate (e.g. always-wipe, or never-wipe) makes a case FAIL,
# so this is not a tautology gate — it catches its own negation.
#
# Usage:  bash test_atm339_reconfigure_detection.sh
# Output: PASS/FAIL per case + a machine-readable result.json under
#         qa-results/host_batch_119/atm339_evidence/.
#
# Parses under sh -n AND bash -n (§11.4.67).

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
EVID_DIR="$PARENT_ROOT/qa-results/host_batch_119/atm339_evidence"
mkdir -p "$EVID_DIR"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

PASS=0
FAIL=0
LOG="$EVID_DIR/test_run.log"
: > "$LOG"

log() { echo "$*" | tee -a "$LOG"; }

# ── The decision predicate UNDER TEST ────────────────────────────────────
# Mirrors compile-libvlc.sh §586+ exactly:
#   VLC_EXPECTED_CONTRIB_PREFIX="${VLC_SRC_DIR}/contrib/${TARGET_TUPLE}"
#   if [ -e "$VLC_BUILD_DIR/config.status" ] && \
#      ! grep -q -- "$VLC_EXPECTED_CONTRIB_PREFIX" "$VLC_BUILD_DIR/config.status" ; then
#        rm -rf "$VLC_BUILD_DIR"; reconfigure
#   fi
# Returns 0 (WIPE) when a stale config.status exists whose recorded prefix
# differs from the expected one; returns 1 (KEEP) otherwise.
reconfigure_needed() {
    # $1 = VLC_BUILD_DIR, $2 = expected contrib prefix
    _bdir="$1"
    _expected="$2"
    if [ -e "$_bdir/config.status" ] && \
       ! grep -q -- "$_expected" "$_bdir/config.status" 2>/dev/null; then
        return 0   # WIPE / reconfigure
    fi
    return 1       # KEEP
}

# Helper: build a fake configure-output build dir.
# Writes a config.status whose baked-in --with-contrib path is $1.
make_build_dir() {
    _dir="$1"
    _baked_prefix="$2"
    mkdir -p "$_dir"
    # A real config.status embeds the absolute --with-contrib path; mirror it.
    cat > "$_dir/config.status" <<EOF
#! /bin/sh
# Generated by configure (synthetic fixture for ATM-339 test)
ac_cs_config="'--host=aarch64-linux-android' '--with-contrib=${_baked_prefix}' '--prefix=${_dir}/install/'"
S["AOM_CFLAGS"]="-I${_baked_prefix}/include"
S["AVCODEC_CFLAGS"]="-I${_baked_prefix}/include"
EOF
    # config.h presence is what the OLD §592 guard checks; include it so we
    # prove the NEW guard catches what the old one missed.
    echo "#define HAVE_ICONV 1" > "$_dir/config.h"
}

assert() {
    # $1 = case label, $2 = expected verdict (WIPE|KEEP), $3 = actual rc (0=WIPE,1=KEEP)
    _label="$1"; _want="$2"; _rc="$3"
    if [ "$_rc" = "0" ]; then _got="WIPE"; else _got="KEEP"; fi
    if [ "$_got" = "$_want" ]; then
        log "  PASS: $_label — verdict=$_got (expected $_want)"
        PASS=$((PASS + 1))
    else
        log "  FAIL: $_label — verdict=$_got (expected $_want)"
        FAIL=$((FAIL + 1))
    fi
}

log "=== ATM-339 reconfigure-detection hermetic test ==="
log "workdir: $WORK"

# ── CASE 1: same prefix (in-place rebuild — host configured, host rebuild) ─
# The checkout is at the SAME absolute path it was configured at.
C1_SRC="$WORK/case1_src"
C1_PREFIX="$C1_SRC/contrib/aarch64-linux-android"
C1_BUILD="$C1_SRC/build-android-aarch64-linux-android"
make_build_dir "$C1_BUILD" "$C1_PREFIX"
if reconfigure_needed "$C1_BUILD" "$C1_PREFIX"; then RC1=0; else RC1=1; fi
assert "CASE1 same-prefix" "KEEP" "$RC1"
# Proof the dir would be preserved:
[ -e "$C1_BUILD/config.status" ] && log "    evidence: $C1_BUILD/config.status present, prefix matches -> no wipe"

# ── CASE 2: changed prefix (host-configured dir reused under /aosp mount) ──
# The build dir's config.status records the HOST path; the current checkout
# location (the container's /aosp...) differs → must reconfigure.
C2_SRC="$WORK/case2_src"
C2_HOST_PREFIX="/run/media/operator/DATA/Projects/Android_15/.../contrib/aarch64-linux-android"
C2_NOW_PREFIX="$C2_SRC/contrib/aarch64-linux-android"   # e.g. /aosp/.../contrib/...
C2_BUILD="$C2_SRC/build-android-aarch64-linux-android"
make_build_dir "$C2_BUILD" "$C2_HOST_PREFIX"            # baked HOST path
if reconfigure_needed "$C2_BUILD" "$C2_NOW_PREFIX"; then RC2=0; else RC2=1; fi
assert "CASE2 changed-prefix" "WIPE" "$RC2"
log "    evidence: config.status baked '$C2_HOST_PREFIX' but current is '$C2_NOW_PREFIX' -> reconfigure"

# ── CASE 3: no config.status (fresh build dir) ───────────────────────────
# Guard is on the existing-config.status path; a fresh dir is left to the
# natural configure step (the §592 `[ ! -e config.h ]` path), no spurious wipe.
C3_SRC="$WORK/case3_src"
C3_PREFIX="$C3_SRC/contrib/aarch64-linux-android"
C3_BUILD="$C3_SRC/build-android-aarch64-linux-android"
mkdir -p "$C3_BUILD"   # empty: no config.status
if reconfigure_needed "$C3_BUILD" "$C3_PREFIX"; then RC3=0; else RC3=1; fi
assert "CASE3 fresh-no-config.status" "KEEP" "$RC3"

# ── CASE 4: source-fidelity — the SHIPPED compile-libvlc.sh predicate ─────
# Guards against this test drifting from the real fix: assert the shipped
# source contains the exact prefix-mismatch predicate this test mirrors.
SHIP_COMPILE="$SCRIPT_DIR/libvlcjni/buildsystem/compile-libvlc.sh"
RC4=1   # default FAIL (not present)
if [ -f "$SHIP_COMPILE" ] && \
   grep -q 'VLC_EXPECTED_CONTRIB_PREFIX=.*VLC_SRC_DIR.*contrib.*TARGET_TUPLE' "$SHIP_COMPILE" && \
   grep -q '! grep -q -- "\$VLC_EXPECTED_CONTRIB_PREFIX" "\$VLC_BUILD_DIR/config.status"' "$SHIP_COMPILE" && \
   grep -q 'rm -rf "\$VLC_BUILD_DIR"' "$SHIP_COMPILE"; then
    RC4=0
fi
if [ "$RC4" = "0" ]; then
    log "  PASS: CASE4 source-fidelity — shipped compile-libvlc.sh carries the ATM-339 predicate"
    PASS=$((PASS + 1))
else
    log "  FAIL: CASE4 source-fidelity — shipped compile-libvlc.sh missing the ATM-339 predicate"
    FAIL=$((FAIL + 1))
fi

# ── CASE 5: source-fidelity — the SHIPPED helper belt-and-suspenders ──────
SHIP_HELPER="$SCRIPT_DIR/build-atmosphere-vlc-player.sh"
RC5=1
if [ -f "$SHIP_HELPER" ] && \
   grep -q 'ATM-339' "$SHIP_HELPER" && \
   grep -q '! grep -q -- "\$_expected_prefix" "\$_bdir/config.status"' "$SHIP_HELPER" && \
   grep -q 'rm -rf "\$_bdir"' "$SHIP_HELPER"; then
    RC5=0
fi
if [ "$RC5" = "0" ]; then
    log "  PASS: CASE5 source-fidelity — shipped helper carries the belt-and-suspenders purge"
    PASS=$((PASS + 1))
else
    log "  FAIL: CASE5 source-fidelity — shipped helper missing the belt-and-suspenders purge"
    FAIL=$((FAIL + 1))
fi

# ── Anti-tautology guard: prove the predicate is real, not always-KEEP ────
# (CASE2 returned WIPE, so the predicate is NOT a constant KEEP.
#  CASE1+CASE3 returned KEEP, so it is NOT a constant WIPE.)
log "=== summary: PASS=$PASS FAIL=$FAIL ==="

# ── Machine-readable result.json (§11.4.69 evidence shape) ────────────────
_ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$EVID_DIR/result.json" <<EOF
{
  "test": "atm339_reconfigure_detection",
  "feature_class": "build_artifact_integrity",
  "timestamp_utc": "$_ts",
  "cases": [
    { "id": "CASE1_same_prefix",        "expected": "KEEP",    "rc": $RC1 },
    { "id": "CASE2_changed_prefix",     "expected": "WIPE",    "rc": $RC2 },
    { "id": "CASE3_fresh_no_config",    "expected": "KEEP",    "rc": $RC3 },
    { "id": "CASE4_source_fidelity_compile", "expected": "PRESENT", "rc": $RC4 },
    { "id": "CASE5_source_fidelity_helper",  "expected": "PRESENT", "rc": $RC5 }
  ],
  "pass": $PASS,
  "fail": $FAIL,
  "verdict": "$( [ "$FAIL" -eq 0 ] && echo PASS || echo FAIL )",
  "boundary": "hermetic logic test of the prefix-mismatch predicate; full end-to-end container VLC build is REQUIRES_BUILD (§12.9, not run here)"
}
EOF
log "evidence: $EVID_DIR/result.json"
log "evidence: $LOG"

if [ "$FAIL" -eq 0 ]; then
    log "OVERALL: PASS"
    exit 0
else
    log "OVERALL: FAIL"
    exit 1
fi
